#!/bin/bash
#
# Git commit-msg hook to enforce Conventional Commits naming conventions.
#

COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Check for Conventional Commit format using conventional-changelog
# Regular expression for Conventional Commits
REGEX='^(feat|fix|docs|style|refactor|test|chore|build|ci|perf|revert|release)(\(\w+\))?:\ .{1,50}(\n\n.*)?(\n\n(BREAKING\ CHANGE:\ .+|.+#\d+))?$'

if ! echo "$COMMIT_MSG" | grep -Eq "$REGEX"; then
    echo "ERROR: Invalid commit message format."
    echo "Commit message should be in the format of:"
    echo "  <type>(<scope>): <description>"
    echo "Examples:"
    echo "  feat(lang): added English"
    echo "  fix: fixed some minor bugs"
    echo "  feat!: Added access rights management"
    echo "For more information, visit: https://www.conventionalcommits.org/"
    exit 1
fi