name: Auto Update PR Title to Follow Conventional Commits

on:
  pull_request:
    branches:
        - "main"
        - "develop"
        - "feature/*"
        - "release/*"
        - "bugfix/*"
        - "hotfix/*"
    types: [opened, edited]

jobs:
  update_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Conventional Commit Message Format
        run: |
          # Define commit type (feat, fix, etc.) based on labels or branch name
          if [[ "${{ github.event.pull_request.labels }}" == *"feature"* ]]; then
            COMMIT_TYPE="feat"
          elif [[ "${{ github.event.pull_request.labels }}" == *"bugfix"* || "${{ github.event.pull_request.labels }}" == *"fix"* ]]; then
            COMMIT_TYPE="fix"
          else
            COMMIT_TYPE="chore"
          fi

          # Optionally extract scope from branch name or title (e.g., feature/scope-description)
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          SCOPE=$(echo $BRANCH_NAME | grep -oE '^[a-zA-Z0-9_-]+')

          # Generate the new PR title using Conventional Commit format
          PR_TITLE="${COMMIT_TYPE}(${SCOPE}): ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})"

          echo "New PR title: $PR_TITLE"

          # Update the PR title with the new Conventional Commit message format
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -d "{\"title\":\"$PR_TITLE\"}"
